(ns thompson.morph-test
  (:require [clojure.test :refer :all]
            [thompson.fsa :refer :all]
            [thompson.morph :refer [nfa->dfa]]
            [thompson.search :refer [nfa-accepts? dfa-accepts?]]))

;; PATTERN: (a{1,3}|(b*c))d{2}?(ef)+
(def nfa (succ (alt (rng (sym \a)
                         1 3)
                    (succ (star (sym \b))
                          (sym \c)))
               (opt (rng (sym \d)
                         2))
               (plus (succ (sym \e)
                           (sym \f)))))
(def dfa (nfa->dfa nfa))


(def string-1 "addef")
(def string-2 "aaddef")
(def string-3 "aaaddef")
(def string-4 "aef")
(def string-5 "aaef")
(def string-6 "aaaef")
(def string-7 "addefefef")
(def string-8 "aaddefefef")
(def string-9 "aaaddefefef")
(def string-10 "aefefef")
(def string-11 "aaefefef")
(def string-12 "aaaefefef")
(def string-13 "cddef")
(def string-14 "bcddef")
(def string-15 "bbcddef")
(def string-16 "cef")
(def string-17 "bcef")
(def string-18 "bbcef")
(def string-19 "cddefefef")
(def string-20 "bcddefefef")
(def string-21 "bbcddefefef")
(def string-22 "cefefef")
(def string-23 "bcefefef")
(def string-24 "bbcefefef")

(def string-25 "ddef")
(def string-26 "aadd")
(def string-27 "aaaaddef")
(def string-28 "aefe")
(def string-29 "addaef")
(def string-30 "aaaeff")
(def string-31 "adddefefef")
(def string-32 "aadefefef")
(def string-33 "aaaddefefefe")
(def string-34 "abbcefefef")
(def string-35 "bbcaaefefef")
(def string-36 "aaaefefefdd")
(def string-37 "cddefddef")
(def string-38 "bcaaddef")
(def string-39 "bbcaddef")
(def string-40 "cbbef")
(def string-41 "bcefa")
(def string-42 "bbcefd")
(def string-43 "cddefdefef")
(def string-44 "bddcddefefef")
(def string-45 "bbcaaaddefefef")
(def string-46 "aacefefef")
(def string-47 "bacefefef")
(def string-48 "efbbcefefef")


(deftest equivalency-test
  (testing "Testing equivalency of FSAs."
    (is (= (nfa-accepts? nfa string-1)
           (dfa-accepts? dfa string-1))
        "String 1")
    (is (= (nfa-accepts? nfa string-2)
           (dfa-accepts? dfa string-2))
        "String 2")
    (is (= (nfa-accepts? nfa string-3)
           (dfa-accepts? dfa string-3))
        "String 3")
    (is (= (nfa-accepts? nfa string-4)
           (dfa-accepts? dfa string-4))
        "String 4")
    (is (= (nfa-accepts? nfa string-5)
           (dfa-accepts? dfa string-5))
        "String 5")
    (is (= (nfa-accepts? nfa string-6)
           (dfa-accepts? dfa string-6))
        "String 6")
    (is (= (nfa-accepts? nfa string-7)
           (dfa-accepts? dfa string-7))
        "String 7")
    (is (= (nfa-accepts? nfa string-8)
           (dfa-accepts? dfa string-8))
        "String 8")
    (is (= (nfa-accepts? nfa string-9)
           (dfa-accepts? dfa string-9))
        "String 9")
    (is (= (nfa-accepts? nfa string-10)
           (dfa-accepts? dfa string-10))
        "String 10")
    (is (= (nfa-accepts? nfa string-11)
           (dfa-accepts? dfa string-11))
        "String 11")
    (is (= (nfa-accepts? nfa string-12)
           (dfa-accepts? dfa string-12))
        "String 12")
    (is (= (nfa-accepts? nfa string-13)
           (dfa-accepts? dfa string-13))
        "String 13")
    (is (= (nfa-accepts? nfa string-14)
           (dfa-accepts? dfa string-14))
        "String 14")
    (is (= (nfa-accepts? nfa string-15)
           (dfa-accepts? dfa string-15))
        "String 15")
    (is (= (nfa-accepts? nfa string-16)
           (dfa-accepts? dfa string-16))
        "String 16")
    (is (= (nfa-accepts? nfa string-17)
           (dfa-accepts? dfa string-17))
        "String 17")
    (is (= (nfa-accepts? nfa string-18)
           (dfa-accepts? dfa string-18))
        "String 18")
    (is (= (nfa-accepts? nfa string-19)
           (dfa-accepts? dfa string-19))
        "String 19")
    (is (= (nfa-accepts? nfa string-20)
           (dfa-accepts? dfa string-20))
        "String 20")
    (is (= (nfa-accepts? nfa string-21)
           (dfa-accepts? dfa string-21))
        "String 21")
    (is (= (nfa-accepts? nfa string-22)
           (dfa-accepts? dfa string-22))
        "String 22")
    (is (= (nfa-accepts? nfa string-23)
           (dfa-accepts? dfa string-23))
        "String 23")
    (is (= (nfa-accepts? nfa string-24)
           (dfa-accepts? dfa string-24))
        "String 24")
    (is (= (nfa-accepts? nfa string-25)
           (dfa-accepts? dfa string-25))
        "String 25")
    (is (= (nfa-accepts? nfa string-26)
           (dfa-accepts? dfa string-26))
        "String 26")
    (is (= (nfa-accepts? nfa string-27)
           (dfa-accepts? dfa string-27))
        "String 27")
    (is (= (nfa-accepts? nfa string-28)
           (dfa-accepts? dfa string-28))
        "String 28")
    (is (= (nfa-accepts? nfa string-29)
           (dfa-accepts? dfa string-29))
        "String 29")
    (is (= (nfa-accepts? nfa string-30)
           (dfa-accepts? dfa string-30))
        "String 30")
    (is (= (nfa-accepts? nfa string-31)
           (dfa-accepts? dfa string-31))
        "String 31")
    (is (= (nfa-accepts? nfa string-32)
           (dfa-accepts? dfa string-32))
        "String 32")
    (is (= (nfa-accepts? nfa string-33)
           (dfa-accepts? dfa string-33))
        "String 33")
    (is (= (nfa-accepts? nfa string-34)
           (dfa-accepts? dfa string-34))
        "String 34")
    (is (= (nfa-accepts? nfa string-35)
           (dfa-accepts? dfa string-35))
        "String 35")
    (is (= (nfa-accepts? nfa string-36)
           (dfa-accepts? dfa string-36))
        "String 36")
    (is (= (nfa-accepts? nfa string-37)
           (dfa-accepts? dfa string-37))
        "String 37")
    (is (= (nfa-accepts? nfa string-38)
           (dfa-accepts? dfa string-38))
        "String 38")
    (is (= (nfa-accepts? nfa string-39)
           (dfa-accepts? dfa string-39))
        "String 39")
    (is (= (nfa-accepts? nfa string-40)
           (dfa-accepts? dfa string-40))
        "String 40")
    (is (= (nfa-accepts? nfa string-41)
           (dfa-accepts? dfa string-41))
        "String 41")
    (is (= (nfa-accepts? nfa string-42)
           (dfa-accepts? dfa string-42))
        "String 42")
    (is (= (nfa-accepts? nfa string-43)
           (dfa-accepts? dfa string-43))
        "String 43")
    (is (= (nfa-accepts? nfa string-44)
           (dfa-accepts? dfa string-44))
        "String 44")
    (is (= (nfa-accepts? nfa string-45)
           (dfa-accepts? dfa string-45))
        "String 45")
    (is (= (nfa-accepts? nfa string-46)
           (dfa-accepts? dfa string-46))
        "String 46")
    (is (= (nfa-accepts? nfa string-47)
           (dfa-accepts? dfa string-47))
        "String 47")
    (is (= (nfa-accepts? nfa string-48)
           (dfa-accepts? dfa string-48))
        "String 48")))
